import { and, asc, desc, eq } from "drizzle-orm"
import { bookings, paymentIntents, paymentTransactions } from "@/db/schema"
import type { EffectivePrincipal } from "@/server/core/auth/principal"
import { getDb } from "@/server/core/database/client"
import { forbidden, notFound } from "@/server/core/errors/app-error"
import { getEnv } from "@/server/core/env"
import { getMinioClient } from "@/server/core/storage/minio"

export function assertCustomerPaymentOwner(principal: EffectivePrincipal, customerProfileId: string | null) {
  if (principal.actorClass !== "customer" || !principal.customerProfileId) throw forbidden("FORBIDDEN", "Customer account required")
  if (customerProfileId !== principal.customerProfileId) throw forbidden("TENANT_SCOPE_VIOLATION", "Payment belongs to another customer")
}
function storedReceiptKey(ref: string | null) { return ref?.startsWith("object:") ? ref.slice(7) : null }
function mapRow(row: PaymentRow) { const key = storedReceiptKey(row.rawReceiptRef); return { id: row.id, bookingId: row.bookingId, bookingReference: row.bookingReference, intentId: row.intentId, provider: row.provider, providerTransactionId: row.providerTransactionId, purpose: row.purpose, type: row.type, status: row.status, amountMillimes: row.amountMillimes.toString(), currency: "TND" as const, createdAt: row.createdAt.toISOString(), receiptAvailable: Boolean(key), receiptPath: key ? `/api/v1/account/payments/${row.id}/receipt` : null, downloadPath: key ? `/api/v1/account/payments/${row.id}/receipt` : null } }
type PaymentRow = { id: string; bookingId: string; bookingReference: string; customerProfileId: string | null; intentId: string; provider: string; providerTransactionId: string | null; purpose: string; type: string; status: string; amountMillimes: bigint; createdAt: Date; rawReceiptRef: string | null }
const selection = { id: paymentTransactions.id, bookingId: bookings.id, bookingReference: bookings.reference, customerProfileId: bookings.customerProfileId, intentId: paymentIntents.id, provider: paymentIntents.provider, providerTransactionId: paymentTransactions.providerTransactionId, purpose: paymentIntents.purpose, type: paymentTransactions.type, status: paymentTransactions.status, amountMillimes: paymentTransactions.amountMillimes, createdAt: paymentTransactions.createdAt, rawReceiptRef: paymentTransactions.rawReceiptRef }
function baseQuery() { return getDb().select(selection).from(paymentTransactions).innerJoin(paymentIntents, eq(paymentTransactions.intentId, paymentIntents.id)).innerJoin(bookings, eq(paymentIntents.bookingId, bookings.id)) }
export async function listOwnedPayments(principal: EffectivePrincipal) { assertCustomerPaymentOwner(principal, principal.customerProfileId); const rows = await baseQuery().where(eq(bookings.customerProfileId, principal.customerProfileId!)).orderBy(desc(paymentTransactions.createdAt)); return rows.map(mapRow) }
export async function getOwnedPayment(principal: EffectivePrincipal, paymentId: string) { const [row] = await baseQuery().where(eq(paymentTransactions.id, paymentId)).limit(1); if (!row) throw notFound("Payment not found"); assertCustomerPaymentOwner(principal, row.customerProfileId); return mapRow(row) }
export async function getBookingPaymentTimeline(principal: EffectivePrincipal, bookingId: string) { const booking = await getDb().query.bookings.findFirst({ where: eq(bookings.id, bookingId), with: { snapshot: true } }); if (!booking) throw notFound("Booking not found"); assertCustomerPaymentOwner(principal, booking.customerProfileId); const rows = await baseQuery().where(and(eq(bookings.id, bookingId), eq(bookings.customerProfileId, principal.customerProfileId!))).orderBy(asc(paymentTransactions.createdAt)); return { bookingId, bookingReference: booking.reference, paymentMode: booking.paymentMode, currency: "TND" as const, totalMillimes: booking.snapshot?.commissionableMillimes.toString() ?? "0", events: rows.map(mapRow) } }
export async function downloadOwnedReceipt(principal: EffectivePrincipal, paymentId: string) { const receipt = await getOwnedPayment(principal, paymentId); if (!receipt.receiptAvailable) throw notFound("Stored receipt not found"); const key = receipt.downloadPath && (await baseQuery().where(eq(paymentTransactions.id, paymentId)).limit(1))[0]?.rawReceiptRef?.slice(7); if (!key) throw notFound("Stored receipt not found"); try { await getMinioClient().statObject(getEnv().MINIO_PRIVATE_BUCKET, key); const stream = await getMinioClient().getObject(getEnv().MINIO_PRIVATE_BUCKET, key); return { stream, contentType: "application/pdf", filename: `wheelio-${receipt.bookingReference}-${receipt.id}.pdf` } } catch { throw notFound("Stored receipt not found") } }
