import type { RentalOffer } from "@/lib/search-types"

export const SEARCH_OFFERS: RentalOffer[] = [
  {
    id: "tn-eco-clio-01",
    modelName: "Renault Clio",
    category: "economy",
    categoryLabel: "Economy",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 5,
    bags: 2,
    transmission: "manual",
    fuel: "petrol",
    airConditioning: true,
    agency: {
      name: "Medina Cars Tunis",
      logo: "/agencies/medina-cars.svg",
      rating: 4.6,
      reviewCount: 214,
      city: "Tunis",
      locationLabel: "Tunis-Carthage Airport",
    },
    confirmation: "instant",
    cancellation: "free",
    cancellationNote: "Free cancellation up to 48h before pickup",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "meet_greet",
    pickupMethodNote: "Meet & greet at Tunis-Carthage arrivals",
    totalPriceTnd: 420,
    depositTnd: 800,
    recommendedScore: 91,
    highlights: ["Airport meet & greet", "City-friendly size"],
    included: ["Airport surcharge", "Basic protection", "Second driver on request"],
  },
  {
    id: "tn-cmp-208-02",
    modelName: "Peugeot 208",
    category: "compact",
    categoryLabel: "Compact",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 5,
    bags: 2,
    transmission: "automatic",
    fuel: "petrol",
    airConditioning: true,
    agency: {
      name: "Carthage Drive",
      logo: "/agencies/carthage-drive.svg",
      rating: 4.8,
      reviewCount: 389,
      city: "Tunis",
      locationLabel: "Tunis-Carthage Airport",
    },
    confirmation: "instant",
    cancellation: "free",
    cancellationNote: "Free cancellation up to 24h before pickup",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "counter",
    pickupMethodNote: "Desk in Terminal A arrivals hall",
    totalPriceTnd: 510,
    depositTnd: 1000,
    recommendedScore: 94,
    sponsored: true,
    highlights: ["Automatic", "Strong agency rating"],
    included: ["Collision damage waiver (basic)", "Airport fee", "Local taxes"],
  },
  {
    id: "tn-int-corolla-03",
    modelName: "Toyota Corolla",
    category: "intermediate",
    categoryLabel: "Intermediate",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 4,
    bags: 3,
    transmission: "automatic",
    fuel: "hybrid",
    airConditioning: true,
    agency: {
      name: "Atlas Mobility",
      logo: "/agencies/atlas-mobility.svg",
      rating: 4.7,
      reviewCount: 176,
      city: "Tunis",
      locationLabel: "Tunis Centre",
    },
    confirmation: "instant",
    cancellation: "partial",
    cancellationNote: "50% refund up to 72h before pickup",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "delivery",
    pickupMethodNote: "Hotel or Airbnb delivery in Greater Tunis",
    totalPriceTnd: 680,
    depositTnd: 1200,
    recommendedScore: 88,
    highlights: ["Hybrid", "Delivery available"],
    included: ["Delivery within 15 km", "Hybrid fuel efficiency", "AC"],
  },
  {
    id: "tn-suv-tucson-04",
    modelName: "Hyundai Tucson",
    category: "suv",
    categoryLabel: "SUV",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 5,
    bags: 4,
    transmission: "automatic",
    fuel: "diesel",
    airConditioning: true,
    agency: {
      name: "Sahara Auto Rent",
      logo: "/agencies/sahara-auto.svg",
      rating: 4.5,
      reviewCount: 142,
      city: "Hammamet",
      locationLabel: "Hammamet centre",
    },
    confirmation: "request",
    cancellation: "free",
    cancellationNote: "Free cancellation until agency confirms",
    mileage: "limited",
    mileageNote: "250 km/day, then 0.45 TND/km",
    pickupMethod: "delivery",
    pickupMethodNote: "Delivery to Hammamet / Enfidha hotels",
    totalPriceTnd: 890,
    depositTnd: 1500,
    recommendedScore: 82,
    highlights: ["Family luggage space", "Coastal trips"],
    included: ["Child seat available", "Roadside assistance"],
  },
  {
    id: "tn-van-trafic-05",
    modelName: "Renault Trafic",
    category: "van",
    categoryLabel: "Van",
    orSimilar: false,
    image:
      "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?auto=format&fit=crop&w=1200&q=80",
    seats: 9,
    doors: 4,
    bags: 6,
    transmission: "manual",
    fuel: "diesel",
    airConditioning: true,
    agency: {
      name: "Groupe Location Sahel",
      logo: "/agencies/groupe-sahel.svg",
      rating: 4.3,
      reviewCount: 98,
      city: "Sousse",
      locationLabel: "Sousse / Monastir",
    },
    confirmation: "request",
    cancellation: "non_refundable",
    cancellationNote: "Non-refundable after confirmation",
    mileage: "limited",
    mileageNote: "300 km/day included",
    pickupMethod: "counter",
    pickupMethodNote: "Monastir Airport partner desk",
    totalPriceTnd: 1120,
    depositTnd: 2000,
    recommendedScore: 74,
    highlights: ["9 seats", "Group travel"],
    included: ["Airport fee", "Third-party liability"],
  },
  {
    id: "tn-lux-eclass-06",
    modelName: "Mercedes-Benz E-Class",
    category: "luxury",
    categoryLabel: "Luxury",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 4,
    bags: 3,
    transmission: "automatic",
    fuel: "petrol",
    airConditioning: true,
    agency: {
      name: "Prestige Tunisie",
      logo: "/agencies/prestige-tunisie.svg",
      rating: 4.9,
      reviewCount: 67,
      city: "Tunis",
      locationLabel: "La Marsa / Tunis",
    },
    confirmation: "instant",
    cancellation: "free",
    cancellationNote: "Free cancellation up to 72h before pickup",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "meet_greet",
    pickupMethodNote: "Private meet & greet with name board",
    totalPriceTnd: 1680,
    depositTnd: 3000,
    recommendedScore: 86,
    highlights: ["Business travel", "Premium fleet"],
    included: ["Premium cover package option", "Meet & greet", "Full tank policy options"],
  },
  {
    id: "tn-eco-i10-07",
    modelName: "Hyundai i10",
    category: "economy",
    categoryLabel: "Economy",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80",
    seats: 4,
    doors: 5,
    bags: 1,
    transmission: "manual",
    fuel: "petrol",
    airConditioning: true,
    agency: {
      name: "Djerba Easy Rent",
      logo: "/agencies/djerba-easy.svg",
      rating: 4.4,
      reviewCount: 121,
      city: "Djerba",
      locationLabel: "Djerba-Zarzis Airport",
    },
    confirmation: "instant",
    cancellation: "free",
    cancellationNote: "Free cancellation up to 48h before pickup",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres on Djerba",
    pickupMethod: "meet_greet",
    pickupMethodNote: "Djerba-Zarzis Airport meet & greet",
    totalPriceTnd: 390,
    depositTnd: 700,
    recommendedScore: 84,
    highlights: ["Island trips", "Low deposit"],
    included: ["Airport fee", "Basic protection"],
  },
  {
    id: "tn-cmp-golf-08",
    modelName: "Volkswagen Golf",
    category: "compact",
    categoryLabel: "Compact",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 5,
    bags: 2,
    transmission: "automatic",
    fuel: "diesel",
    airConditioning: true,
    agency: {
      name: "Nord Auto Location",
      logo: "/agencies/nord-auto.svg",
      rating: 4.2,
      reviewCount: 88,
      city: "Tunis",
      locationLabel: "Tunis Centre",
    },
    confirmation: "request",
    cancellation: "partial",
    cancellationNote: "Full refund until 5 days before pickup",
    mileage: "limited",
    mileageNote: "200 km/day included",
    pickupMethod: "counter",
    pickupMethodNote: "Tunis Centre branch, Avenue Habib Bourguiba area",
    totalPriceTnd: 560,
    depositTnd: 1100,
    recommendedScore: 77,
    highlights: ["City centre pickup", "Diesel efficiency"],
    included: ["City branch pickup", "AC", "USB charging"],
  },
  {
    id: "tn-suv-sportage-09",
    modelName: "Kia Sportage",
    category: "suv",
    categoryLabel: "SUV",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 5,
    bags: 4,
    transmission: "automatic",
    fuel: "petrol",
    airConditioning: true,
    agency: {
      name: "Carthage Drive",
      logo: "/agencies/carthage-drive.svg",
      rating: 4.8,
      reviewCount: 389,
      city: "Tunis",
      locationLabel: "Tunis-Carthage Airport",
    },
    confirmation: "instant",
    cancellation: "free",
    cancellationNote: "Free cancellation up to 24h before pickup",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "counter",
    pickupMethodNote: "Airport desk, shuttle not required",
    totalPriceTnd: 940,
    depositTnd: 1600,
    recommendedScore: 90,
    highlights: ["Instant confirmation", "Unlimited km"],
    included: ["Airport fee", "Basic CDW", "Additional driver option"],
  },
  {
    id: "tn-int-octavia-10",
    modelName: "Skoda Octavia",
    category: "intermediate",
    categoryLabel: "Intermediate",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 4,
    bags: 3,
    transmission: "manual",
    fuel: "diesel",
    airConditioning: true,
    agency: {
      name: "Enfidha Rent Plus",
      logo: "/agencies/enfidha-rent.svg",
      rating: 4.1,
      reviewCount: 54,
      city: "Enfidha",
      locationLabel: "Enfidha-Hammamet Airport",
    },
    confirmation: "request",
    cancellation: "free",
    cancellationNote: "Free cancellation before agency accepts",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "meet_greet",
    pickupMethodNote: "Enfidha-Hammamet Airport meet & greet",
    totalPriceTnd: 610,
    depositTnd: 1000,
    recommendedScore: 79,
    highlights: ["Large boot", "Hammamet access"],
    included: ["Airport meet & greet", "AC"],
  },
  {
    id: "tn-eco-sandero-11",
    modelName: "Dacia Sandero",
    category: "economy",
    categoryLabel: "Economy",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 5,
    bags: 2,
    transmission: "manual",
    fuel: "petrol",
    airConditioning: true,
    agency: {
      name: "Sfax Direct Cars",
      logo: "/agencies/sfax-direct.svg",
      rating: 4.0,
      reviewCount: 73,
      city: "Sfax",
      locationLabel: "Sfax city desk",
    },
    confirmation: "instant",
    cancellation: "non_refundable",
    cancellationNote: "Non-refundable rate",
    mileage: "limited",
    mileageNote: "150 km/day included",
    pickupMethod: "counter",
    pickupMethodNote: "Sfax city centre office",
    totalPriceTnd: 350,
    depositTnd: 600,
    recommendedScore: 71,
    highlights: ["Lowest total", "Local branch"],
    included: ["Basic liability", "City pickup"],
  },
  {
    id: "tn-lux-5series-12",
    modelName: "BMW 5 Series",
    category: "luxury",
    categoryLabel: "Luxury",
    orSimilar: true,
    image:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    seats: 5,
    doors: 4,
    bags: 3,
    transmission: "automatic",
    fuel: "diesel",
    airConditioning: true,
    agency: {
      name: "Prestige Tunisie",
      logo: "/agencies/prestige-tunisie.svg",
      rating: 4.9,
      reviewCount: 67,
      city: "Tunis",
      locationLabel: "La Marsa / Tunis",
    },
    confirmation: "request",
    cancellation: "partial",
    cancellationNote: "Free until 7 days before, then 30% fee",
    mileage: "unlimited",
    mileageNote: "Unlimited kilometres",
    pickupMethod: "delivery",
    pickupMethodNote: "White-glove delivery in Tunis / La Marsa",
    totalPriceTnd: 1890,
    depositTnd: 3500,
    recommendedScore: 80,
    highlights: ["Executive sedan", "Delivery"],
    included: ["Premium assist", "Delivery fee waived in Tunis"],
  },
]

export const PRICE_BOUNDS = {
  min: Math.min(...SEARCH_OFFERS.map((o) => o.totalPriceTnd)),
  max: Math.max(...SEARCH_OFFERS.map((o) => o.totalPriceTnd)),
}

export const DEPOSIT_BOUNDS = {
  min: Math.min(...SEARCH_OFFERS.map((o) => o.depositTnd)),
  max: Math.max(...SEARCH_OFFERS.map((o) => o.depositTnd)),
}
